# Single-stage build
FROM node:22

# Create /app and set as working dir
WORKDIR /app

# Copy backend code into /app/node-backend
COPY node-backend ./node-backend

# Copy shared folder into /app/shared
COPY shared ./shared

# Set working dir to node-backend for commands
WORKDIR /app/node-backend

# Install dependencies
RUN npm install

# Generate Prisma client
RUN npx prisma generate

EXPOSE 5000

CMD ["npm", "run", "start"]
