-- CreateEnum
CREATE TYPE "STATUS" AS ENUM ('PENDING_REVIEW', 'SHORTLISTED', 'REJECTED', 'ACCEPTED');

-- AlterTable
ALTER TABLE "JobApplication" ADD COLUMN     "ai_score" INTEGER,
ADD COLUMN     "status" "STATUS" NOT NULL DEFAULT 'PENDING_REVIEW';
